### ISSUE TITLE
How to get parameters properly / regex patterns not working ?

### ISSUE THREAD

**Issue by agregator123** [dannyvankooten/PHP-Router#101]
In 1.1Alpha i use this:

```php
$collection->attachRoute(new PHPRouter\Route('/sitemap/info.xml', [
    '_controller' => 'App\Controllers\Sitemap::Sitemap',
    'methods' => ['POST','GET'],
    'parameters'=> ['template_file'=>'ajax'],
]));
```
and `get_object_vars($route)['_config']['parameters']['template_file']` to get "ajax" value, but now in last version this not working.

How to make something like this ?

**Comment by agregator123** [comment]
And this: '/details/:id/:id=:id' no longer work....

**Comment by agregator123** [comment]
work-around for the second:
```
$template_file = "";
foreach((array)$route as $v => $k) {
   $template_file.= preg_replace("/[^a-za-z]/", "",$k['parameters']['template_file']);
}
```

Now i need a solution for the regex-like urls in routers because i have seo urls.

**Comment by agregator123** [comment]
Any replies ? Please fix this issue...

**Comment by antoine-pous** [comment]
You can get named parameters with the optionnal argument on `setFilters` method. See #54 for more informations.

Can you provide the full router code for your broken routes please?

**Comment by agregator123** [comment]
```
  $collection->attachRoute(new PHPRouter\Route('/details/:id/:id=:id', [
      '_controller' => 'App\Controllers\Details::Details',
      'methods' => ['POST','GET'],
      'parameters'=> ['template_file'=>'details'],
  ]));
```

**Comment by agregator123** [comment]
Now i try:
```
$route = new PHPRouter\Route('/details/:id/:id=:id',[
'_controller' => 'App\Controllers\Details::Details',
'methods' => ['POST','GET'],
'parameters'=> ['template_file'=>'details'],
]);
$route->setFilters([':id' => '([^a-zA-Z0-9]+)'], true);
$collection->attachRoute($route);
```
but still not working...

**Comment by antoine-pous** [comment]
@malukenho it's look like preg_quote on regex broke the matching in Router.php:120

I can't anymore investigate before tuesday, if you can do something it's cool :+1:

**Comment by agregator123** [comment]
Thanks for your time.. My site still offline 2 days because this... 
I hope to quickly solve this problem. I will wait.

**Comment by agregator123** [comment]
And it will be cool to back this in work:
get_object_vars($route)['_config']['parameters']['template_file'] 

this work-around:
```
$template_file = "";
foreach((array)$route as $v => $k) {
   $template_file.= preg_replace("/[^a-za-z]/", "",$k['parameters']['template_file']);
}
```

is not cool.
or something like this $route->config['parameters']['template_file'];
I'm using mustache and directly pass template variable from routes into $tpl = $mustache->loadTemplate($template_file);
It's easy and fast...

**Comment by antoine-pous** [comment]
Test the `hotfix-101` branch and tell me if it solve the routing issue please

**Comment by agregator123** [comment]
Yes, it works! :)
Can you add a method for get parameters with simple line, something like this:
$route->config['parameters']['template_file'];

This is very important for me.

**Comment by antoine-pous** [comment]
Normally `$route->getParameters()` return an array with `['paramName' => 'val']`

**Comment by agregator123** [comment]
it returns array(0) { } for me...

**Comment by antoine-pous** [comment]
You try it on the right route?

**Comment by agregator123** [comment]
Yes, every my route have 
'parameters'=> ['template_file'=>'template_file_name'],

**Comment by agregator123** [comment]
I add  var_dump($route->getParameters()); after
$route = $router->matchCurrentRequest();
and gives my 
array(0) { }

some of my routes before $router = new PHPRouter\Router($collection); line:

```
$collection->attachRoute(new PHPRouter\Route('/ajax/get_cities_based_on_country', [
    '_controller' => 'App\Controllers\Ajax_Cities::Ajax_Cities',
    'methods' => ['POST','GET'],
    'parameters'=> ['template_file'=>'ajax'],
]));

$collection->attachRoute(new PHPRouter\Route('/ajax/get_countries', [
    '_controller' => 'App\Controllers\Ajax_Countries::Ajax_Countries',
    'methods' => ['POST','GET'],
    'parameters'=> ['template_file'=>'ajax'],
]));

$collection->attachRoute(new PHPRouter\Route('/sitemap/info.xml', [
    '_controller' => 'App\Controllers\Sitemap::Sitemap',
    'methods' => ['POST','GET'],
    'parameters'=> ['template_file'=>'ajax'],
]));

$collection->attachRoute(new PHPRouter\Route('/fortumo/fortumo', [
    '_controller' => 'App\Controllers\Fortumo::Fortumo',
    'methods' => ['POST','GET'],
    'parameters'=> ['template_file'=>'ajax'],
]));
```

**Comment by agregator123** [comment]
Yeah... Everything is great! This is the best router class for me. Thank you!

**Comment by antoine-pous** [comment]
Ok i fixed it, update from `hotfix-101` branch

**Comment by agregator123** [comment]
Thanks again!
