### ISSUE TITLE
Follow PHP version support

### ISSUE THREAD

**Issue by antoine-pous** [dannyvankooten/PHP-Router#105]
I think we should follow the [supported versions of PHP](http://php.net/supported-versions.php) and update PHP Router dependencies.

We could create a branch when we increase the required version of PHP. So users can install easily legacy version with composer.

Currently i work on PR #114, i would like made it for PHP 5.6. I know we shouldn't support anymore PHP 5.6 but this version is used by many users and hosting services.

I therefore propose to support, for the last time, PHP 5.6 with the PR #114. After this release we should provide only security fixes until *31 Dec 2018*.

When this PR was released we can start to work for PHP7.0, PHP7.1 support and follow the official support calendar.

I find it unfortunate not to provide a final version for php 5.6.

I'll modify PR #114 based on your opinions.

**Comment by malukenho** [comment]
There's no support for `5.6.*` other than for security issues. It doesn't need to maintain  ancient php versions, if someone is using this old versions, just use a PHPRouter php `5.*` compatible version.

**Comment by antoine-pous** [comment]
No more answers, we drop definitely PHP5 support.
