### ISSUE TITLE
question mark not working

### ISSUE THREAD

**Issue by agregator123** [dannyvankooten/PHP-Router#118]
I'm using last version (with hotfix 101) on PHP 7 and question marks in url's not working. In oldest version is working properly.

When i have:
`url: "ajax/chat_remove_message/?id=" + id,`
in ajax and:
```
$collection->attachRoute(new PHPRouter\Route('/ajax/chat_remove_message/:id', [
...........
]);
```
not working... It gives me 404 error page...
If question mark is removed - everything is normal, but i want to use this question mark because is easy to use $_GET to get specific vars from url.
Maybe the problem is regex patterns in php router ? 
Please, fix it if is possible.

**Comment by lpotherat** [comment]
If you want to use get parameters, juste remove the ":id" part => $collection->attachRoute(new PHPRouter\Route('/ajax/chat_remove_message/', []);

**Comment by agregator123** [comment]
solved
