### ISSUE TITLE
cant download

### ISSUE THREAD

**Issue by raffacabofrio** [dannyvankooten/PHP-Router#122]
>composer require dannyvankooten/php-router

  [InvalidArgumentException]
  Could not find package dannyvankooten/php-router at any version for your mi
  nimum-stability (stable). Check the package spelling or your minimum-stabil
  ity

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest]
 [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--
ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|
--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<
packages>]...

**Comment by codingphasedotcom** [comment]
yea i'm having same issue

**Comment by Bytheway001** [comment]
Same issue here

**Comment by antoine-pous** [comment]
Check issue #79
