### ISSUE TITLE
Regex and passing values

### ISSUE THREAD

**Issue by bennetgallein** [dannyvankooten/PHP-Router#124]
* PHPRouter version: dev-master
* PHP version: 7.2

Hi, I'm currently facing a small challenge where I didn't found any solution for in the README or the Issues.

I want to have this: Access `/id/1` and I want to pass the `1` over to the Controller. I've tried many things and am stuck on this for 3 hours now. Help is much apprecicated!

This is my current code (reset everything):
```php
<?php
require("vendor/autoload.php");

use Angle\Engine\Router\Collection;
use Angle\Engine\Router\Route;
use Angle\Engine\Router\Router;
use \Angle\Engine\Template\Engine;

use Tracy\Debugger;

Debugger::enable();

define("MYSQL_HOST", "localhost");
define("MYSQL_USER", "bennet");
define("MYSQL_PASSWORD", "root");
define("MYSQL_DATABASE", "bennet");

$collection = new Collection();

$engine = new Engine();

$collection->attach(new Route("/", array(
    "_controller" => '\Blog\Controllers\Overview::display',
    "parameters" => ["engine" => $engine],
    "methods" => 'GET'
)));

// id url
$collection->attachRoute(new Route("/id/:id", array(
    "_controller" => '\Blog\Controllers\Overview::display',
    "parameters" => ["engine" => $engine],
    "methods" => 'GET'
)));


$router = new Router($collection);
$router->matchCurrentRequest();
```

**Comment by malukenho** [comment]
It's indeed a bug. I'll look into it.

**Comment by bennetgallein** [comment]
Thanks a lot!

**Comment by bennetgallein** [comment]
But why the 2.0.0 milstone if the 1.0.0 isn't even out yet? In my optionion that is a really important thing to have

**Comment by malukenho** [comment]
@bennetgallein could you try it again? I just sent a patch to `master`.

I did the following test:

```php
<?php

namespace Blog\Controllers {
    class Overview {
        public function display($engine) {
            var_dump($engine);
        }
    }
}

namespace {
    require __DIR__ . '/vendor/autoload.php';

    use PHPRouter\RouteCollection;
    use PHPRouter\Router;
    use PHPRouter\Route;

    $collection = new RouteCollection();

    $collection->attachRoute(new Route('/id/:id', array(
        '_controller' => '\Blog\Controllers\Overview::display',
        'parameters' => ['id' => '\d+'],
        'methods' => 'GET'
    )));

    $router = new Router($collection);
    $router->matchCurrentRequest();
}
```

**Comment by bennetgallein** [comment]
From my first look that seems to be working, but I also need those other parameters, like `$engine`.. With those in place, that won't work for me.

**Comment by bennetgallein** [comment]
I was testing with this:
```php
$collection->attachRoute(new Route("/id/:id/:nd", array(
    "_controller" => '\Blog\Controllers\Overview::display',
    "parameters" => ["engine" => $engine, 'id' => '\d+', 'nd' => '\d+'],
    "methods" => 'GET'
)));
```
And got this error: `Too few arguments to function Blog\Controllers\Overview::display(), 2 passed and exactly 3 expected`

The array of parameter for call_user_func_array is the following:
```
array (2)
id => "2"
nd => "3"
```
A picture 
![e840bac9b4c2c4148945552a7b0ce311](https://user-images.githubusercontent.com/15325891/39409710-359df484-4bec-11e8-9b7e-18ee08605aca.png)

**Comment by bennetgallein** [comment]
![aa](https://user-images.githubusercontent.com/15325891/39409847-383ee246-4bee-11e8-8991-37db8cb6de19.png)

**Comment by bennetgallein** [comment]
```
public function setParameters(array $parameters)
    {
        $this->parameters = array_merge($this->parameters, $parameters);
    }
```

Using this in the Route class added my additional parameters to the array. So they don't get overwritten by the match() function in the Router itself. Gonna test this a little bit more.
