### ISSUE TITLE
Overwrite ?

### ISSUE THREAD

**Issue by Pok4** [dannyvankooten/PHP-Router#129]
* PHPRouter version: 1.2 alpha
* PHP version 7.4:

hello guys, i use this beautiful router class, but i have a question.

I have a admin panel route like this in my core.php:

```
$collection->attachRoute(new PHPRouter\Route('/admin/custom_pages_ext.php', [
    '_controller' => 'App\Controllers\Admin\Custom_Pages_Ext::Custom_Pages_Ext',
    'methods' => ['POST','GET'],
    'parameters'=> ['template_file'=>'admin_custom_pages_ext'],
]));
```

look at the url, now i want to overwrite somewhere in my controllers with this:

```
$this->router->attachRoute(new PHPRouter\Route('/admin/custom_pages_ext.php?apage=view_tickets&ajax=1', [
                '_controller' => 'MyController::ajax',
		'methods' => ['POST','GET'],
		'parameters'=> ['template_file'=>'ajax'],
 ]));
```
the url is the same, but with some url parameters. I want to overwrite first with second one, to make a ajax call.
Maybe not overwrite, but i want to detect exact address to make ajax call in this controller (in the second code). Now this second code not working.

the exact code is like this:
```

class the_tickets extends \App\Controllers\BaseController  {
  
  public function __construct() {
    parent::__construct(); 
  }
  

  public function custom_page_admin() {
     if (strpos($_SERVER['REQUEST_URI'], 'apage=view_tickets') !== false) {
		 
       //make a router for ajax call
	 $this->router->attachRoute(new PHPRouter\Route('/admin/custom_pages_ext.php?apage=view_tickets&ajax=1', [
    '_controller' => 'ajax',
		'methods' => ['POST','GET'],
		'parameters'=> ['template_file'=>'ajax'],
     ]));
 

      return $this->admin_form();
     }

```

**Comment by lpotherat** [comment]
Hi Pok, 

I think you misunderstood the concept behind PHPRouter, GET parameters (aka the query string, everything after "?") are not part of the pattern. 
I may be wrong, but I think PHPRouter cannot use the query string to match controllers.

And by the way, your routes have to be configured once and for all at your program initialisation, you don't want to attach new routes on weird conditions like this.

**Comment by Pok4** [comment]
but i want to make a ajax call on current controller.
I have extensions in my cms system and its hard for me to make ajax call. When i make ajax call i need to create a new file, to create new db connection and so on... I need to make a ajax call with router for my specific extensions. Yes, maybe you are right about intialisation, but this is small modules which is part of the system and they are enable/disable by a button.
They are separate from the system and is uploaded in folder like ext/
I use event dispatcher + container to create them.

They call from BaseController like this:
```
<?php
namespace App\Controllers;

class BaseController {

  public function __construct() {
  
	//Load All Enabled Extensions
    load_extensions(); //@includes/functions.php

  }
```

load_extension function have:
```
//Load extensions
function load_extensions() {
  global $dbh,$container,$dispatcher;
  $checker = $dbh->query('SELECT ext_name FROM '.getenv("DB_PREFIX").'ext WHERE ext_active=1');    
  if($checker->rowCount() > 0) {
    while($row=$checker->fetch(PDO::FETCH_ASSOC)){
      $ext_name = $row['ext_name'];
      if(file_exists(__DIR__.'/../ext/'.$ext_name.'/ext.php')) {
        require_once(__DIR__.'/../ext/'.$ext_name.'/ext.php');
      }
    }
  }
}
```

And part of the one of the extensions is:
```
<?php 
if(count(get_included_files()) == 1) exit("Direct access not permitted."); //Don't edit
//Your Extension Script
class the_tickets extends \App\Controllers\BaseController  {
  
  public function __construct() {
    parent::__construct(); 
  }
  

  public function custom_page_admin() {
     if (strpos($_SERVER['REQUEST_URI'], 'apage=view_tickets') !== false) {
		 
		 	 //make a router for ajax call
	 $this->router->attachRoute(new PHPRouter\Route('/admin/custom_pages_ext.php?apage=view_tickets&ajax=1', [
    '_controller' => 'ajax',
		'methods' => ['POST','GET'],
		'parameters'=> ['template_file'=>'ajax'],
     ]));
 

      return $this->admin_form();
     }
	 

  }

```

**Comment by lpotherat** [comment]
You cannot use PHPRouter to manage the query string, i think your issue is not with PHPRouter but with the architecture of your program.

You may find more assistance on StackOverflow maybe, since your question is not related to PHPRouter library.

**Comment by Pok4** [comment]
Ok, thank you.
