### ISSUE TITLE
Custom parameters for _controller in routes

### ISSUE THREAD

**Issue by Pok4** [dannyvankooten/PHP-Router#131]
* PHPRouter version: 1.2alpha
* PHP version 7.4

Hello guys,

it's possible to do something like this:
```
$collection->attachRoute(new PHPRouter\Route('/ajax/ext/:id/:id', [
'_controller' => 'ext\{{:id}}\{{:id}}::ajax',
'methods' => ['POST','GET'],
'parameters'=> ['template_file'=>'ajax'],
]));

```
i want to get current id like $_GET['id'] in controllers for custom url. I want the results to be the same from the route url.

if url is like this:
**/ajax/ext/test/test1**
the controller will be:
**'_controller' => 'ext\test\test1::ajax',**

**Comment by lpotherat** [comment]
Hi, 
This is not possible, you have to declare one route for each controller. Plus, you should not use the same parameter name multiple time in the same route.

The only way you could do this is like this : 

Create a GenericController class with ajax method

```
$collection->attachRoute(new PHPRouter\Route('/ajax/ext/:ns/:cls', [
    '_controller' => 'ext\GenericController::ajax',
    'methods' => ['POST','GET'],
    'parameters'=> ['template_file'=>'ajax'],
]));
```

Then in your GenericController::ajax method : 

```
function ajax($args){
    $ns = $args['ns'];
    $cls = $args['cls'];

    $className = "\\$ns\\$cls";

    $inst = new $className();
    $inst->ajax();
}
```


But it defeat the purpose of the library since your doing the mapping work yourself at the end....

**Comment by Pok4** [comment]
i do this:

```
if(strpos($_SERVER['REQUEST_URI'], 'ajax/ext/')) {
$ext_author = get_string_between($_SERVER['REQUEST_URI'],'ajax/ext/','/');
$ext_name = get_string_between($_SERVER['REQUEST_URI'],'ajax/ext/'.$ext_author.'/','/');

$collection->attachRoute(new PHPRouter\Route('/ajax/ext/:id/:id', [
'_controller' => "ext\\".$ext_author."\\".$ext_name."::ajax",
'methods' => ['POST','GET'],
'parameters'=> ['template_file'=>'ajax'],
]));
}
```

the function is:
```
function get_string_between($string, $start, $end, $inclusive = false){
  $fragments = explode($start, $string, 2);
  if (isset($fragments[1])) {
    $fragments = explode($end, $fragments[1], 2);
    if ($inclusive) {
       return $start.$fragments[0].$end;
    } else {
       return $fragments[0];
    }
  }
  return false;
}
```
and it works perfect...
i just want a more pleasant way.

**Comment by lpotherat** [comment]
I'm afraid there is no better way than discussed here

**Comment by Pok4** [comment]
Thank you.
