### ISSUE TITLE
problem when is touching a url 

### ISSUE THREAD

**Issue by Pok4** [dannyvankooten/PHP-Router#132]
* PHPRouter version: 1.2alpha
* PHP version 7.4

Sorry for the title, i don't know what to write there :) My english is not good at all...

I have a problem, but i don't know that the problem is in the router or with my code...

Ok, i have this:

`$admin_url = (strpos($_SERVER['REQUEST_URI'], '/admin/') !== false); //if /admin/ string is in url we change mustache loader`

and this:
```
//if admin is touching admin/, we redirect.
if ($admin_url) {
  require_once(__DIR__.'/admin/routes.php');
  require_once(__DIR__.'/admin/includes/admin_functions.php');
}
```

i'm using mustache for template engine and i put this:
`'loader' => $admin_url ? new Mustache_Loader_FilesystemLoader('admin/template',['extension' => '.html']) : new Mustache_Loader_FilesystemLoader(__DIR__."/template/".get_style()."", ['extension' => '.html']),`

i have and this:
```
//if we no found page -> print 404
if(!$route) {
  header('Location: '.url().'/404/');
  exit;
} 
```

Everything works great, i can access any page of my site, even one with seo urls, they are defined like this:
```
$collection->attachRoute(new PHPRouter\Route('/', [
    '_controller' => 'App\Controllers\News::News',
    'methods' => ['GET','POST'],
    'parameters'=> ['template_file'=>'index'],
]));

$collection->attachRoute(new PHPRouter\Route('/:id', [
    '_controller' => 'App\Controllers\News::News',
    'methods' => ['POST','GET'],
    'parameters'=> ['template_file'=>'index'],
]));

$collection->attachRoute(new PHPRouter\Route('/core.php', [
    '_controller' => 'App\Controllers\News::News',
    'methods' => ['GET','POST'],
    'parameters'=> ['template_file'=>'index'],
]));
```

I can access and my admin panel, but when i touch my-site.com/adminbb its shows a page with no resources... JS/CSS resources can't load, there is no template file for this page.
When i touch /admin/ everything is ok, but when i touch /adminbb/ admincc/ adminANYTHING - and the resources and template file not load. Only text with some functions on blank background, you know it what i mean :)

I don't know where is the problem. I dont have a router for adminbb/ or adminANYTHING... Maybe the problem is from routers about news, i posted them in the code above... 

Can you help me to fix this problem ?

**Comment by Pok4** [comment]
Guys, i added this one:
```
    /* If we touch site.com/admin[string] we redirect it, don't remove this, because can be appeared some bugs */
	if(strpos($_SERVER['REQUEST_URI'], '/admin') !== false) { 
	 header('location: '.url().'');
	}
```

in top of my News method and the problem is gone.

Can you suggest me a better way, or this is ok for now ?

**Comment by lpotherat** [comment]
Hi, 

It is your route here : 
```
$collection->attachRoute(new PHPRouter\Route(**'/:id'**, [
    '_controller' => 'App\Controllers\News::News',
    'methods' => ['POST','GET'],
    'parameters'=> ['template_file'=>'index'],
]));
```
It catches all urls /* , so /adminbb is one of them.

You should not mix weird conditions with PHPRouter routes, all you have to do is to have a clear set of well defined routes to access your software and all will be nice.

Just create a route before this one like this : 
```
$collection->attachRoute(new PHPRouter\Route(**'/admin:id/'**, [
    '_controller' => ' Your correspondant admin controller  ',
    'methods' => ['POST','GET'],
    'parameters'=> ['template_file'=>'index'],
]));
```
Don't forget the trailing slash

**Comment by Pok4** [comment]
Thanks.
