### ISSUE TITLE
Custom parameters passing

### ISSUE THREAD

**Issue by Pok4** [dannyvankooten/PHP-Router#134]
* PHPRouter version: 1.2alpha
* PHP version 8.1

Hi again, guys :)

I started a topic in stackoverflow for my previous problem and there is some replies: https://stackoverflow.com/questions/71241075/php-8-unknown-named-parameter-dannyvankooten-router/71241345?noredirect=1#comment125927353_71241345

They told me to remove this line from code:
`'parameters'=> ['template_file'=>'ajax'],`

to my script start working, but this is so important ...
I started this one to give a suggestion to making edit in router code to start working like this :)

This is important, because i use template engine mustache and i pass the variables like this:
`$tpl = $mustache->loadTemplate(get_object_vars($route)['_config']['parameters']['template_file']);`

and this:
`$tpl = $mustache->loadTemplate($route->getParameters()['template_file']);`

both working in php 5.4> and <php7.4

Without this ones i'm lost and my CMS can't working... This is very important...
Its so easy to set a template file in routes and to catch this one from my template system... It's very clear and pleasant way..
If you help me to start this working i will be very happy :)

Thanks in advance.

**Comment by lpotherat** [comment]
Hi again, 

As you can see in the composer.json file, this library is not yet compatible with PHP > 8.0.

But you can make changes a propose a PR, but I don't think this library is well maintained ...

**Comment by Pok4** [comment]
Ok, i make a research how to fix this and i will give a example if i find a proper way :) I'm not gonna close this for now...

**Comment by Pok4** [comment]
Guys, i found a way (workaround, but it works)

open Route.php and find:
`call_user_func_array(array($instance, $this->action), $this->parameters);`

change it to:
`call_user_func_array(array($instance, $this->action), array_values($this->parameters));`

and the custom parameters still works.

I will be very happy if you make it the changes to 1.2alpha.

**Comment by lpotherat** [comment]
Just like I said, look at the [contributing guide](https://github.com/dannyvankooten/PHP-Router/blob/dfd121cffc435e7d5483c9bfeef0f8ed25afee19/.github/CONTRIBUTING.md), and make a Pull Request, and it will be visible to maintainers. But I think you'll have to make your own fork of this library and modify it like you want.

**Comment by Pok4** [comment]
i make a request https://github.com/dannyvankooten/PHP-Router/pull/135 
This is my first pull request, sorry if i make a mistake... 

I'm so glad to use 1.2.0alpha, everything is working fine, but this 2 things about regex (https://github.com/dannyvankooten/PHP-Router/issues/124) and this one here need to be done...

Can you give me the example how to use my fork on composer.json ? I see a examples on stackoverflow, but i can't make things work...
I want to make changes on 1.2.0 and i want to use it like: composer require pok4/php-router:1.2.0alpha
But when i'm on 1.2.0alpha on my own fork - i cant make the changes to the file, it sais: you must be on a branch...

Maybe 1.2.0 is hotfix-101 ? I think thats is because i see the name @antoine-pous

**Comment by lpotherat** [comment]
Again, if you're having trouble with Github, Composer, your code or anything non related to this library, please go to to official documentations of these tools or to stackoverflow, they're dedicated to support and learning.
