### ISSUE TITLE
Get route params

### ISSUE THREAD

**Issue by CawaKharkov** [dannyvankooten/PHP-Router#46]
One more idea, it would be nice if user can get matched controller and action name from PHPRouter\Route

**Comment by malukenho** [comment]
@CawaKharkov now it's possible by using `getParameters()` on Route object or getting this via arguments inside method.

**Comment by CawaKharkov** [comment]
Just a half of  year ;)

**Comment by malukenho** [comment]
@CawaKharkov sorry for this, I'll spend a more time on `PHP-Router` this month.
