### ISSUE TITLE
update .htaccess info in readme

### ISSUE THREAD

**Issue by Skenji** [dannyvankooten/PHP-Router#64]
I am using this useful and simple router in one of my projects and I had a problem with the assets (css/js/fonts/etc) due to the configuration in the .htaccess file. I recommend to update it to avoid problems. It worked for me this way, but it causes problems with URL's parameters.

```
Options +FollowSymLinks
RewriteEngine On
RewriteRule ^(\w+)$ index.php [NC,L]
```

**Comment by Skenji** [comment]
I updated the .htaccess to this:

Options +FollowSymLinks
RewriteEngine On
RewriteCond  %{REQUEST_FILENAME} !-f
RewriteCond  %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ index.php [NC,L]

and it worked fine with parameters and assets :)

**Comment by Antoine-Pous** [comment]
This is not a really good idea, with your .htaccess file we can call any existing file. The best way is ignoring directly your subdirectories who's contain your files or exclude files with their extension.
```
RewriteEngine on
RewriteBase /

# Redirect all requests to index.php ignoring listed files extensions
RewriteCond %{REQUEST_URI} !\.(css|js|eot)$
# Redirect all requests to index.php ignoring listed directories
RewriteCond %{REQUEST_URI} !^/?(css|js|fonts|ect)/
RewriteRule ^(.*)$ index.php [L,QSA]
```

**Comment by Skenji** [comment]
Thanks for the advise I will ehance my .htaccess then. I was just pointing this out because it would be more helpful to include something like it in the read me.

I really liked PHP-Router and I'm using it in a project.
