### ISSUE TITLE
How to get params on controller

### ISSUE THREAD

**Issue by ghost** [dannyvankooten/PHP-Router#71]
Hi i've the following route:

$collection->attachRoute(new Route('/fanstore/:id', array(
    '_controller' => 'Controllers\FanstoreController::benefit',
    'methods' => 'GET',)
));

What i must do  to get ':id' on benefit function?

Thanks
----------

EDIT:
On Router.php i delete '+1' on $matches[$key'] and it works
 foreach ($argument_keys as $key => $name) {
                    if (isset($matches[$key])) {
                        $params[$name] = $matches[$key];
                    }
                }

**Comment by edouardkombo** [comment]
Many thanks to you :)

**Comment by malukenho** [comment]
@ghost merged. Thanks 🍻
