### ISSUE TITLE
Example.php

### ISSUE THREAD

**Issue by marcospgp** [dannyvankooten/PHP-Router#73]
"Have a look at the example.php file"

Wonder where that is

**Comment by mcbmcb0** [comment]
i had the same question - if you download one of the old release zip files you'll find one in there. must have got lost in the composer structure

**Comment by malukenho** [comment]
Hey @marcospgp,
probably it's a mistake on README file. This `example` file is in the `old-version` branch.

https://github.com/dannyvankooten/PHP-Router/tree/old-version

[]'s
