### ISSUE TITLE
Composer installation failed

### ISSUE THREAD

**Issue by val4o0o0** [dannyvankooten/PHP-Router#79]
I try with:
composer require dannyvankooten/php-router
But I get this:
http://i.imgur.com/2tKfMJp.png

I try with:
composer require dannyvankooten/php-router --dev too (same)

**Comment by malukenho** [comment]
@val4o0o0 try to set `minimum-stability` to `dev`. Put on your `composer.json`:

```json
{
    "minimum-stability": "dev"
}
```

**Comment by val4o0o0** [comment]
Thanks.
