### ISSUE TITLE
Error on install PHP Router with Composer

### ISSUE THREAD

**Issue by D4rkHero** [dannyvankooten/PHP-Router#86]
When I try to install the PHP Router with composer I receive the error below:

>  [InvalidArgumentException]
>   Could not find package dannyvankooten/php-router at any version for your minimum-stability (stable). Check the pack
>   age spelling or your minimum-stability

**Comment by antoine-pous** [comment]
Check issue #79

**Comment by D4rkHero** [comment]
Thanks
