### ISSUE TITLE
Load config as Json Or Yaml to avoid Yaml dependencies

### ISSUE THREAD

**Issue by lpotherat** [dannyvankooten/PHP-Router#87]
Hi, 

I like this package because it's a very simple Router. 
To keep this project very simple and independent, I think it would be nice to allow configs to be in Yaml OR Json format, to avoid the Yaml library dependency.
Yaml mode could also use the php native methods when available ( http://php.net/manual/fr/book.yaml.php )

The objective is to avoid avoidable dependencies.

Have a good day

**Comment by antoine-pous** [comment]
Sorry for the late answer, i had lot of work. I made this changes in a few weeks :)

**Comment by malukenho** [comment]
I guess you can do it on your application/infrastructure level

**Comment by lpotherat** [comment]
@malukenho that's what i've already done, but i thought it would be nice to let the option opened and avoid the yaml dependency.
@antoine-pous I'm watching this project, waiting for the work thanks.

**Comment by malukenho** [comment]
The **thing** is that `yaml` is not a very good format as it seems, I don't know if maintain another `DSL` just to be more friendly pays off.

My suggestion is to create another package that you can install to give you ease yaml support or
create it on your own infrastructure.

If you can create a separated project to give it yaml support, them we can add it to the README and the `suggest` session on composer.

/cc @antoine-pous

**Comment by lpotherat** [comment]
I think there is a misunderstanding, the actual problem is in the class PHPRouter\Config, the method loadFromFile assumes the project have the Symfony\Component\Yaml\Yaml class in the project, witch is a dependency. This dependency is not referenced in the composer.json. So, i suggested a solution with JSON to be more independent.

Maybe the final solution is a separate composer package for the file based configuration.

Thanks for your interest :)

**Comment by malukenho** [comment]
Feel free to send a PR once you have the package finished 🍻
