### ISSUE TITLE
Allow filter configuration via config file

### ISSUE THREAD

**Issue by lpotherat** [dannyvankooten/PHP-Router#88]
We can add filters by code but not via config file, it could be at index 3 of the route config array ?

	{
		"base_path":"/test",
		"routes":{
			"test1": ["/test1/:param1/:param2", "TestController.test1", "GET",{":param1":"([a-f0-9]{32})"}]
		}
	}

**Comment by antoine-pous** [comment]
I fully agree with this suggestion

**Comment by antoine-pous** [comment]
This feature was added to PR #114, JSON is also supported now
